### ISSUE TITLE
无关问题，

### ISSUE THREAD

**Issue by smalldickman** [Dimitri2020007/Actions-OpenWrt#1]
是不是用的云编译啊，看看用的lede的仓库，目前他的golang版本是1.152， lienol的golang版本是1.154，可能是版本不对的原因。。

For more information, see 'go help module-auth'.

Cleaning module download cache (golang/go#27455)

这个是我以前也遇到v2ray 因为golang版本不对便不过去
https://github.com/xiaorouji/openwrt-package/issues/700

修改Makefile 到1.154 看好不好使。。

**Comment by Dimitri2020007** [comment]
日志不够详细，是不是编译trojan-go时候出现的问题？

**Comment by smalldickman** [comment]
> 日志不够详细，是不是编译trojan-go时候出现的问题？

passwall 更新频繁，如果不是用的lienol的openwrt主仓库会有时候不配套，golang版本是会影响trojan-go 或者v2ray的编译（踩过这两种坑），还有个naiveproxy这个也容易出问题，需要多装一两个依赖。。

你的云编译build-openwrt.yml 这个文件拉取的是
env:
  REPO_URL: https://github.com/coolsnowwolf/lede.git
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default

如果加了lienol的应用库就可能会golang版本对不上编不过去。。

**Comment by Dimitri2020007** [comment]
确实是这样子
